controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    

reset_password:
    resource: '../src/Controller/ResetPasswordController.php'
    type: attribute
